import os

#OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")

GROQ_API_KEY = os.environ.get("GROQ_API_KEY")

SAMPLE_RATE = 16000
FRAME_DURATION_MS = 30
FRAME_SIZE = int(SAMPLE_RATE * FRAME_DURATION_MS / 1000)

SILENCE_THRESHOLD_MS = 600
MAX_UTTERANCE_MS = 10000
MIN_CONFIDENCE = 0.55
